name: Publish Python 🐍 distributions 📦 to PyPI and Test PyPI

on:
  push:
    tags:
      - 'test-*'
      - 'release-*'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 based on tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Clean dist directory
      run: rm -rf dist/*
    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish distribution 📦 to Test PyPI
      if: startsWith(github.ref, 'refs/tags/test-')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags/release-')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
