name: Publish Python distributions to Test PyPI & PyPI

on:
  push:
    tags:
      - 'test-*'
      - 'release-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build twine

      - name: Clean dist/
        run: rm -rf dist

      - name: Build distributions
        run: python -m build

      - name: Validate distributions
        run: twine check dist/*

      - name: Publish to Test PyPI
        if: startsWith(github.ref, 'refs/tags/test-')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/release-')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
